name: Get Latest SonarScanner

runs:
  using: 'composite'
  steps:
    - name: check-scanner
      shell: bash
      run: |
        echo "Checking for xml utils" >> $GITHUB_STEP_SUMMARY
        
        if [ -x "$(command -v xmllint)" ]; then
          echo "libxml2-utils is installed"
        else
          echo "libxml2-utils are not installed"
          sudo apt install -y libxml2-utils
        fi
        
        echo "Checking for sonnar-scanner" >> $GITHUB_STEP_SUMMARY
        http_status=$(curl -s -o /dev/null -w "%{http_code}" "https://downloads-cdn-eu-central-1-prod.s3.eu-central-1.amazonaws.com/?delimiter=/&prefix=Distribution%2Fsonar-scanner-cli%2F")

        if [ "$http_status" -ne 200 ]; then
            echo "Error: The URL did not return a status code of 200. Exiting."
            exit 1
        fi

        # Fetch the XML content from the URL
        xml_content=$(curl -s "https://downloads-cdn-eu-central-1-prod.s3.eu-central-1.amazonaws.com/?delimiter=/&prefix=Distribution%2Fsonar-scanner-cli%2F")

        echo "Extracting metadata" >> $GITHUB_STEP_SUMMARY
        
        key=$(echo "$xml_content" | xmllint --xpath "//*[local-name()='Contents'][last()]/*[local-name()='Key' and contains(., 'sonar-scanner-cli-')]" -)

        VERSION=$(echo "$key" | perl -nle 'print $1 if /sonar-scanner-cli-(\d+\.\d+\.\d+\.\d+)/')
        
        LINUX_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$VERSION-linux.zip"
        DARWIN_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$VERSION-macosx.zip"
        WINDOWS_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$VERSION-windows.zip"

        echo "SonarScanner CLI Version: $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"        
        echo "linux=$LINUX_URL" >> "$GITHUB_OUTPUT"        
        echo "darwin=$DARWIN_URL" >> "$GITHUB_OUTPUT"        
        echo "windows=$WINDOWS_URL" >> "$GITHUB_OUTPUT"

outputs:
  version:
    description: 'SonarScanner CLI version'
    value: ${{ steps.check-scanner.outputs.version }}

  linux:
    description: 'SonarScanner Download link for Linux'
    value: ${{ steps.check-scanner.outputs.linux }}

  darwin:
    description: 'SonarScanner Download link for MacOS'
    value: ${{ steps.check-scanner.outputs.darwin }}

  windows:
    description: 'SonarScanner Download link for Windows'
    value: ${{ steps.check-scanner.outputs.windows }}

